# Generated by Django 4.1.7 on 2023-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default_profile_image.jpeg', upload_to='profile_images'),
        ),
    ]
