# Generated by Django 4.1.7 on 2023-02-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loaction',
            new_name='location',
        ),
    ]
